version: '3.9'

services:
  # Django app
  web:
    image: python:3.10.8
    container_name: test-shop-app
    volumes:
      - ./test_shop:/app
    working_dir: /test_shop
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=django-insecure-3)3**x5#-=ogr&3&a=7!fk%ao8cpc2k@l6#l&!rw3c*2yoz6x_
      - DJANGO_ALLOWED_HOSTS=your_allowed_hosts
      - DJANGO_DB_ENGINE=django.db.backends.sqlite3
      - DJANGO_DB_NAME=db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  # Redis cache
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
